# These are supported funding model platforms

github: [mozartrafi, mzrtamp, zhycorp] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: zhycorp # Replace with a single Patreon username
